---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mysql-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql-operator
      version: 0.6.3
      sourceRef:
        kind: HelmRepository
        name: bitpoke-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
    image:
      repository: docker.io/bitpoke/mysql-operator
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "0.7.0-amd64"
    rbac:
      # Specifies whether RBAC resources should be created
      create: true
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
    podSecurityContext:
      runAsNonRoot: true
      # 65532 is the UID for nonroot user from distroless image
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
