apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AQnk/6O+9a7GqTOtocP+,iv:sGI8XQI8FoP1aJgLU9aExvaWISbqSJXeovie9cF/efw=,tag:l9bAUh9mk8gzifcIpf63Dg==,type:str]
    SECRET_CH_DOMAIN: ENC[AES256_GCM,data:T0a3mVOS+Vw54d4=,iv:pHHSUWK8k7F3UWOaQzqFTfgWtrR8DlWEtCRwYumdAgI=,tag:UnA3OkV3gHaYCfCuR0CGCA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:AzkD9UR3YvVLeaoiP5wzAf2/RgM=,iv:50ouAodVHtU+mKDTcw8Gf2tbMONXeru/Y2lzRqq8eNc=,tag:UIdWBeEpUTFp3bEpLZ14UQ==,type:str]
    SECRET_DNS_TARGET: ENC[AES256_GCM,data:vc/03+qUJ64j+oC+r2thCe/oM3IkAeLR+u/Hzw==,iv:XD6fJ/vlipSCk1mWnijuCO0BPceQpIGsHn3acEyRYk8=,tag:CG6FAJF4mfbV3B34OxXcgA==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:T5exoxlyZsqZxmrRXucIpJMPHkYky4CRRmF5Fbo69XpNTLdfSwWu0jMXc3Xc817fDv12HAOIC+0W1iVQTGh3u+ZvCyZr1eQ0H9p69M9J5hBpIG+IiVYAlp0P63D6AjUB2yEGj6CG1QBxprehJg2iEPt29OKaElY2eY0=,iv:FxgBi0MN+58L89EkceerI1cAZ6QdIekF05Kf6T4vEOc=,tag:yFmDoBHF5niq2GBkLvvXsw==,type:str]
    #ENC[AES256_GCM,data:kts04vU=,iv:I9sMTk8KeXiCnpOfFVL/Xsggj6bCprl/kupvWSAMmE4=,tag:xMZlyDMcwXJf0tJ4anYEpg==,type:comment]
    SECRET_OIDC_CLIENT_SECRET_GRAFANA: ENC[AES256_GCM,data:J4OqXkUXVksbBydzj7f32Guo+r6+MMXiKsIXD/NC8NHe6fD4slK4z27loqfQCsigThOh35ZloIewcxKnnm39U/2+Kpc1caOq,iv:K6E5Vc+MwN6WCU1KvFngTlkuiOrqUqWZ03gqBH5y7bE=,tag:T2oIEsWEbt8bPFz+NgUvyQ==,type:str]
    SECRET_OIDC_CLIENT_SECRET_SHARRY: ENC[AES256_GCM,data:Ax9ijTdpGsN1XXxizZlZroJqb9HZIw93IFjyAgME2DzGzRZ4Ieh+IBZP+/PS3mrDLYic01qREgMCkjmoTJ2lBxtClPqFXoNC,iv:NVvVUW/SbI8qbEQlq7vq5FaXqS6QGc2Afc9qx9jDKeg=,tag:UUooY3V/17mHXz5lXh2DQQ==,type:str]
    #ENC[AES256_GCM,data:sbJJqXPZBmXb,iv:AIicm3upbT/n1v6ozZIyiGhOq71mdrqoDXoGNY9VYuA=,tag:OFLG0mVjeLhWZGEUKFscww==,type:comment]
    SECRET_PLEXTOKEN: ENC[AES256_GCM,data:36jDgZpWryIsSGbjtLLR1oChPf0=,iv:2h7ZwpQwHLJzwCYoeFMGq41uzOB6ISPMfU8j6Z/RpR0=,tag:RMzs5x+YgWvwuPXCqMUWaw==,type:str]
    SECRET_SONARR_URL: ENC[AES256_GCM,data:9OB3lhXDoByOy6U23XaDWU3qHCiIZWE=,iv:95YiZvdYceAS/aCFwBJjlOVl+xctbCOAo8QdxSw24iM=,tag:NjgIKmA4sJm0Cce5/H3dMg==,type:str]
    SECRET_SONARR_API_KEY: ENC[AES256_GCM,data:UxQ5OOBL/StzU4hNfertvvvW6e5TxHqaoCPelo1rIL4=,iv:xry7dWzm+mvb7u/4LX/pdC4lkEN6W8GpImG4FZQpN3E=,tag:npdSsTg+SiTrXybIvsJ7Vg==,type:str]
    SECRET_RADARR_URL: ENC[AES256_GCM,data:SY9IJlBTc4iSOSQKuUoug/kZyLIGIxc=,iv:5bcW0bvkzvkpr8HjciEzXXhzp0eNI3Mct9F2jX/PRGI=,tag:RkFv1NIJWwPxxWx9wVdv5A==,type:str]
    SECRET_RADARR_API_KEY: ENC[AES256_GCM,data:R+BEsPWcRqMRQB0e/Db/8ZC6g8jFgsI5Vi7og4kxJtY=,iv:MCs0yDCUCoDZERConzBd1lN73DjCC7xhj4fKTVhV53s=,tag:ZXLoXJ2f6pYhF9qtulyM+A==,type:str]
    SECRET_TAUTULLI_URL: ENC[AES256_GCM,data:q/o5b3KknJOZNSkcERlOZTjgoJg8pQhSkBB3mx0Pj0JgRfBfg3Od3L0hn6Q=,iv:EIcM9poI7Ilm9SOB0CJInEQJemOycHcCyuRAKUEq29M=,tag:AUi3IzisX//YTOT2aKx8BQ==,type:str]
    SECRET_TAUTULLI_API_KEY: ENC[AES256_GCM,data:6/w3LF3aV/hhzqwVDN3SRqs32se3PqlNIEXbgjj/Klc=,iv:E+gY8kJswT+c+OEtykwJwhG8eshDUtFCZCiHvOwLP50=,tag:mgM8RcerCvtavV69seJrzQ==,type:str]
    SECRET_PROWLARR_URL: ENC[AES256_GCM,data:tx+uQp0JqexbQp0SLci8gjoF4Anyll0=,iv:hP6bxxz9ka6oLkdpKuhNbmGBKz8sPf4a5q0P6THHjn4=,tag:9aPo50iwXdtUhefOZPFuaQ==,type:str]
    SECRET_PROWLARR_API_KEY: ENC[AES256_GCM,data:18/rf44X+RJeqe92lEqtPHJeAvULS/wH0dYJhdEVeN8=,iv:uCKJ97M5Uv1sva0hJV1zMgIUvZGuK8jrXr+X+JJI80E=,tag:cnXSf0kPnRueL40CNX/2Pg==,type:str]
    #ENC[AES256_GCM,data:iulkxLHR+g==,iv:5Hz+HTdZUXdbghI7uT6+fFvcTHTXfRdcYtNw4p9Sc9U=,tag:i9GXdAMDWbHJPGFEnVLT3g==,type:comment]
    CODESERVER_PASSWORD: ENC[AES256_GCM,data:CIAckUgeUewOn6eo,iv:hhX5bZvxuAI170XwD1Yyh1+CzhsURMPH6hX+8kvrLhQ=,tag:myv5cpAqTRU7P/y/9BQeLA==,type:str]
    #ENC[AES256_GCM,data:FcPRaiTT,iv:MtdaPsjz+kYmymisIr5jgF8ZTTE4oIdrnpu6mhCLwJ8=,tag:4XVfaTbYRzFenmKCtVC1fA==,type:comment]
    SECRET_MINIO_ACCESSKEY: ENC[AES256_GCM,data:odNvfDY=,iv:g0d58AUoNeusF3Qvf5twnAFL+C3t3VNuyA4f83LlMek=,tag:fWfGQBOy+lhxRLw8HfroQQ==,type:str]
    SECRET_MINIO_SECRETKEY: ENC[AES256_GCM,data:BYIl+WMToImSDaa2hNwS8lPwBCdC/i4zm9ESUYwx,iv:v4wyavKbLnmK/fsqhK2QK9p8EIddX7oyjSJhrbwqFY8=,tag:G/MSTbmWeG0TTIb/JmTB1g==,type:str]
    SECRET_MINIO_BEARERTOKEN: ENC[AES256_GCM,data:aFHUUpvxGCZ/crrr2jh6n8kGbqXPjopV6dJ2VbJhyrEIPJbCm6l7jgRr7G+TFSjMPuPoLxT29WfXhx0cmzBRR6mpR454UWm6b6e/nKYVQUtNODYo6Wj5MAhS6WMGY61hT4g2a8SKbpiKq4cRF+IYMHPLT3Yq13v+0sch3rNqNq+YQOPU9bgs+X6SRIYba5zZooiN+ax95B5cCOVhUyoE78gmAmqIcXDoX1RaiJA+npzLeWO6PYKc1hZlT7Gy3Ql0,iv:q9fzAY+Cp9JWe1+c7Ci2hczdLNBWHOBil9FYpwCgAEk=,tag:MnE1r/r/R0Bqi0qfTewRAQ==,type:str]
    #ENC[AES256_GCM,data:0epvlPUKnGQ=,iv:R0h8HYS3NKjHIZ0yosP7NHNq1wydPtF2k2WovZC9Xto=,tag:4vWBJ0MXeScfPZ9WMB7gpA==,type:comment]
    SECRET_YOUTUBE_TOKEN: ENC[AES256_GCM,data:mCzrgzcVcDqNZdXkp6bZrI6M+DNM9exvJzZyF4NZ4QBSLfKJZDyF,iv:UeQYNCa3VjoHv3+QCJ8Polqc0ISN3XgKp8T+IzLnedE=,tag:Cntf3jQOuZCw3AHD2MY09w==,type:str]
    #ENC[AES256_GCM,data:XVXC3A==,iv:YLRaC2DYj3/c93j56lqU7lKk2ocodVRw900szduQvK8=,tag:R/8/GnDalzKbvy5GSSsReQ==,type:comment]
    NAS_ADDRESS: ENC[AES256_GCM,data:jBHBzqLLUdpvYng=,iv:hAYNKZ4Y6t9lobtr87oZ8f6O/FbqOn6W0iUkxRZamwk=,tag:n180VkxVNXIDP5C90LF8eg==,type:str]
    CSI_USERNAME: ENC[AES256_GCM,data:O5+2Ise8DmQ=,iv:yICNhsjNRn7hSeBv5OVTrFoVBF+0d2EjFta1l4q1wRI=,tag:4LzXWJxnIBK2d8A7EhwvGw==,type:str]
    CSI_PASSWORD: ENC[AES256_GCM,data:D5FOeKPMbgyG+4jV5A==,iv:rGOUXa5NX4FJ2tP0UMWrRtpfuJgltHKanxSAchw454o=,tag:Rvru90y+XjeWFS9suVwoUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUnVVRGhUempRRFAyczJF
            bHZraFM1V2tYaWpnNnlzZzZ3c0l3Q29acFhnCjZJdzNzMkI3Vjl6MEJaS1dMWGt1
            Yk1RNTFVWE5tRkJNbW95VWY0Q21vMFkKLS0tIGZ2U1huTjRUOTZtclowTVBHa3lw
            QmRwenZ2dnRhWWN6V1Rpd21hWUtFdFUK0SJxmwzKrJz0o/+JpokO8keflLaGvJHf
            XNhAaCGFyaHO14DXDPATpmJgarQLJievIZuvB165T2CwhKJfpRZkfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-05T06:56:07Z"
    mac: ENC[AES256_GCM,data:Y6R9HXKoPtHMddZ8HlVTuY5wO0Ub0he3gDHNVh9rJ0ZS5+TgV5I6hCMdpDLGHlg8XXpMnw3teKxJYAx9NPD5aBZmmKbpqjZfShQLWmbBND/pNLmj4zgLBTjNpYOfURmTOS8mbZutD9TCm7qkj2bsOQ0ZULXaq7zgWkinfEjzSeM=,iv:WUzgUTUlOmMlYxO7siWzDZfqnpawOUQINIuZzjZDY+c=,tag:1cYoO11Io9FSyJzmETqd1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
