---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      certificate:
        certManager: true
      serviceMonitor:
        enabled: true
